#+TITLE: Rant sobre a comunidade

** Distanciamento, rant sobre a comunidade.

Aviso de textão: Leia se quiser entender as parada. Senão viva no mundinho do algodão doce, aqui não tem massagem e nem paninho pra vacilação.

Confesso que me distanciei do discord e isso tem me fazido/feito (sla) muito bem, já que há muita toxicidade na parte de 'donos' de servidor, muitos estão arrogantes demais, tem uns que só são donos 'na teoria', isso é desanimador, além é claro, de haver muita trairagem também, *por parte de certas pessoas desleais que nem se quer programam nada e tem que ficar pagando os outros e só sabem dar ls no terminal, segurando fix, tratando solução de problema estrutural como exclusividade, cobrando de quem é opensource sem ter oferecido nada e pedindo pros 'seus' ajoelharem pra ele pq ele é 'foda' kkk baita arrombado do krl...* ~(vlw por quebrar esse na release, mlk, tamo junto)~, 

/Outros que são 'mágicos' com os server files há LITERALMENTE 8 ANOS que não sabiam abrir mapa GM, ou coisas básicas, mas que juram serem os maiorais falando q fizeram td no reverse/ ~(vlw !)!) por quebrar esse aqui tb)~ 

E =alguns nem sabiam instalar ubuntu 22.04 em vps, literalmente 1 click no painel em print q me mandaram, também conhecido como v____l "Oi meu nome é Felipe, moro em Portugal e sou pobre, reforçando o esteriótipo de português ladrão do tempo da colonização brasileira, eu roubei os files de alguém kkk 6 nem tão ligado, ia ajudar mas agora vou ficar com a fix só pra mim, inventei uma pá de mentira pros gado do meu servidor e tudo é roxo no meu servidor de cu sujo" Ah vcs não tem a fix? que pena... 10k eu te vendo a fix.=\\ 
*Se fodeu arrombado! Agora pega 10k em piroca de plástico pra enfiá nesse teu rabo com prolapso seu fdp.* ~(a maior emoção foi quebrar esse, vlw d vdd)~ 

Além dos 'donos' tem também os seus """ /GMs/ """ que acham que estão no direito de fazer tudo, e isso inclui atitudes fora de jogo, como por exemplo: /vir com continha alt fazer graça achando que é a turma da mônica e que ngm percebeu/, ou /dizer que não escolheria um lado depois de uma treta que beneficiou alguém de maneira CLARA e ficar do lado de vacilão fdp sabendo do que aconteceu/, ou, até mesmo cobrar 20 conto numa gaia, *PUTA QUE PARIU*, e *se vc paga, C É BURRO MANO*, tmnsc.

Quer ter um GF que você concorda com tudo? Abra seu servidor LOCALMENTE, aprenda a mexer com os bagulho, aí joga nele e não enche o saco, não dê trabalho... E não haja como se vc fosse o 'rei do mundo/camarote', você tá usando binários que nem são seus, que você nem sabe como funciona, abre teu olho pra largá a mão de ser besta/idiota/pnc.

Finalizando: *SE VOCÊ NÃO SABE MEXER COM LINUX NEM NA VM, ESQUECE VPS, JOGUE UM SERVER QUE JÁ EXISTE*, ou jogue o seu local, senão *você vai se complicar, ser atacado e ficar dando trabalho, aí a expulsão do grupo do discord é certa e seu choro é bem livre.*
